// generated by Fast Light User Interface Designer (fluid) version 1.0300

#ifndef ImageWindow_h
#define ImageWindow_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Progress.H>
#include "plotWindow.h"
class ImageWindow {
public:
  ImageWindow();
  plotWindow       *plot;                   // the plot window

};
#endif
